package com.springboottutorial.servlate;

import com.springboottutorial.model.User;
import com.springboottutorial.service.UserService;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.util.List;

@WebServlet("/users")
public class UserServlet extends HttpServlet {

    private UserService userService = new UserService(); // tight coupling

    public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
        Integer id = Integer.parseInt(request.getParameter("id"));
        String name = request.getParameter("name");
        String email = request.getParameter("email");
        String mobileNo = request.getParameter("mobile");

        if(id == null || name == null || email == null || mobileNo == null){
            response.setStatus(404);
            response.setContentType("application/json");
            response.getWriter().write("{\n" +
                    "    \"message\" : \"Some field are missing\"\n" +
                    "}");
        }

        User user = new User(name, email, mobileNo, id);
        User createdUser = userService.createUser(user);

        // 201 -> resource created
        response.setStatus(201);
        response.setContentType("application/json");
        response.getWriter().write("{\n" +
                "    \"message\" : \"User added successfully\"\n" +
                "}");
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        String idParam = request.getParameter("id");

        if (idParam == null) { // get all
            List<User> users = userService.getAllUsers();
            response.setStatus(201);
            response.setContentType("application/json");
            response.getWriter().write(usersToJson(users));
            return;
        }

        Integer id = Integer.parseInt(idParam);
        User userRes = userService.getUserById(id);

        if(userRes == null){
            response.setStatus(404);
            response.setContentType("application/json");
        }

        // 200 -> resource fetched successfully
        response.setStatus(201);
        response.setContentType("application/json");
        response.getWriter().write(userToJson(userRes));
    }

    public void doPut(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse){

    }

    public void doDelete(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse){

    }

    private String userToJson(User user){
        return "{\n" +
                "    \"id\":" + user.getId() + ",\n" +
                "    \"name\":" + user.getName() + ",\n" +
                "    \"email\": "+ user.getEmail() +",\n" +
                "    \"mobile\" : "+ user.getMobileNO() +"\n" +
                "}";
    }

    private String usersToJson(List<User> users){
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("[");

        for(int i = 0; i<users.size(); i++){
            stringBuilder.append(userToJson(users.get(i)));

            if(i < users.size()-1)
                stringBuilder.append(",");
        }

        stringBuilder.append("]");
        return stringBuilder.toString();
    }
}

/*
    One servlet handles all type of http request. In servlates http requests are class specific not method specific.
    To use the web app we need to use url like this - localhost:8080/servlet-crud-app/users
    here servlet-crud-app is war file name generated by maven.
    To user only servlet we need jakarta servlet api dependency
 */