package com.springboottutorial.crud_spring_boot_demo.service;

import com.springboottutorial.crud_spring_boot_demo.entity.Student;
import com.springboottutorial.crud_spring_boot_demo.repository.StudentRepository;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RequestBody;

import java.util.List;
import java.util.Optional;

@Service // internally uses @Component
public class StudentService {

    private final StudentRepository studentRepository;

    public StudentService(StudentRepository studentRepository){
        this.studentRepository = studentRepository;
    }

    public Student createStudent(Student studentReq){
        studentReq.setDeleted(false); // by default always false

//        System.out.println("Inside student service");
        Student studentRes = studentRepository.save(studentReq);
//        System.out.println("Exiting student service");

        return studentRes;
    }

    public Student getStudent(Long id){
//        Optional<Student> studentRes = studentRepository.findById(id);

        // It will be generated by jpa in runtime
        Optional<Student> studentRes = studentRepository.findByIdAndDeletedIsFalse(id);

        return studentRes.orElse(null);
    }

    public List<Student> getAllStudent(){
//        return studentRepository.findAll();
        return studentRepository.findByDeletedIsFalse();
    }

    public Student updateStudent(Long id, @RequestBody Student studentReq){
        // if student doesn't exist don't update it
//        Optional<Student> existingStudent = studentRepository.findById(id);
        Optional<Student> existingStudent = studentRepository.findByIdAndDeletedIsFalse(id);

        if(existingStudent.isEmpty())
            return null;

        Student studentToSave = existingStudent.get();

        studentToSave.setName(studentReq.getName());
        studentToSave.setAge(studentReq.getAge());
        studentToSave.setEmail(studentReq.getEmail());
        studentToSave.setSubject(studentReq.getSubject());
        studentToSave.setRollNo(studentReq.getRollNo());
        studentToSave.setDeleted(false);

        return studentRepository.save(studentToSave);
    }

    /*
        deleteStudent is work as hard delete, it has very specific use case and even if the record is soft deleted
        I can delete the record using this hard delete.
     */
    public Student deleteStudent(Long id){
        // if student doesn't exist don't update it
        Optional<Student> existingStudent = studentRepository.findById(id);

        if(existingStudent.isEmpty())
            return null;

        studentRepository.deleteById(id);
        return existingStudent.get();
    }

    public boolean deleteStudentSoftly(Long id){
        // if record is already soft deleted then don't delete it
        Optional<Student> existingStudent = studentRepository.findByIdAndDeletedIsFalse(id);

        if(existingStudent.isEmpty())
            return false;

        existingStudent.get().setDeleted(true);
        studentRepository.save(existingStudent.get());
        return true;
    }
}

/*
    Business logic comes under service classes
 */